### ISSUE TITLE
seq-take with streams shorter than given number

### ISSUE THREAD

**Issue by ghost** [NicolasPetton/stream#1]
Hi!

E.g.

```
(seq-into-sequence (seq-take (stream (list 1 2 3)) 4))
```

==> [error with not so useful error message]

Since the number of elements of a stream is not always known, the above could just return

```
(1 2 3)
```

If you don't want this for consistency reasons, it would probably be good to raise a special kind of error in this case, e.g. 'end-of-stream or so.  I still would miss a mean to say "make a stream of the first N elements of a given stream, or just the elements of that stream if shorter than N elements".

Thanks!

**Comment by NicolasPetton** [comment]
Raising a special error seems to be the best solution IMO, and the most consistent.  Would it be good enough for you?

**Comment by ghost** [comment]
Nicolas Petton notifications@github.com writes:

> Raising a special error seems to be the best solution IMO, and the
> most consistent.  Would it be good enough for you?

Not really, to be honest.  In my example

```
(seq-into-sequence (seq-take (stream (list 1 2 3)) 4))
```

I would be able to catch the error (an improvement no doubt), but if I
want the (1 2 3), it would still not be possible.

Maybe a separate function would be appropriate?  Because I think this is
a common use case when working with streams: cut after N elements, but
don't error if the stream contains fewer elements.

**Comment by NicolasPetton** [comment]
Another function would be fine with me (something specific to stream.el maybe?).  Do you have a good name in mind?

**Comment by ghost** [comment]
Nicolas Petton notifications@github.com writes:

> Another function would be fine with me (something specific to
> stream.el maybe?).

Yes.

> Do you have a good name in mind?

Mmh.  `stream-cut-after'?`stream-restrict'?

**Comment by NicolasPetton** [comment]
Hmm, I don't really like that names, because I don't understand what it will do just by reading the function name. What about `stream-take`, that would take an extra boolean argument to ignore end of stream exceptions?  Then `seq-take` would use `stream-take`, but not use this extra argument for consistency with the other implementations of `seq-take`.

**Comment by NicolasPetton** [comment]
After thinking more about this, I actually think that streams should really behave like lists: instead of returning `nil`, `seq-rest` will return the empty stream, so `seq-take' would behave like it does for lists.

**Comment by NicolasPetton** [comment]
This commit fixes the issue: https://github.com/NicolasPetton/stream/commit/fab2fca5d01958c745853625e0924f5b6735293d

**Comment by ghost** [comment]
Nicolas Petton notifications@github.com writes:

> This commit fixes the issue: fab2fca

In the way I suggested AFAIU.

One comment on

> (defun stream-rest (stream)
>    "Return a stream of all but the first element of STREAM."
> -  (cdr (stream--force (cadr stream))))
> -  (or (cdr (stream--force (cadr stream)))
> -      (stream-empty)))

According to the doc of stream-make, the cdr of a stream-force is always
a stream, hence never nil (nil is not stream-p).  So AFAIU the above
change should not be needed.

BTW, is it a mistake that `stream-p' is not called`streamp'?  AFAIK
when the predicate name is one word, "p" is appended without a hyphen.

**Comment by NicolasPetton** [comment]
Michael Heerdegen notifications@github.com writes:

> According to the doc of stream-make, the cdr of a stream-force is always
> a stream, hence never nil (nil is not stream-p).  So AFAIU the above
> change should not be needed.

I will update the doc. `nil` is used to terminate the stream.

> BTW, is it a mistake that `stream-p' is not called`streamp'?  AFAIK
> when the predicate name is one word, "p" is appended without a hyphen.

That's indeed a mistake.

**Comment by ghost** [comment]
Nicolas Petton notifications@github.com writes:

> Hmm, I don't really like that names, because I don't understand what
> it will do just by reading the function name. What about stream-take,
> that would take an extra boolean argument to ignore end of stream
> exceptions? Then seq-take would use stream-take, but not use this
> extra argument for consistency with the other implementations of
> seq-take.

I don't understand the consistency argument any more.  The generic
`seq-take' implementation:

--8<---------------cut here---------------start------------->8---
(cl-defgeneric seq-take (seq n)
  "Return a subsequence of SEQ with its first N elements.
The result is a sequence of the same type as SEQ.

If N is a negative integer or zero, an empty sequence is
returned."
  (seq-subseq seq 0 (min (max n 0) (seq-length seq))))
--8<---------------cut here---------------end--------------->8---

already behaves like I suggested for streams: if fewer
elements are there, return all elements.

BTW, calling `seq-length' in that defgeneric seems quite inefficient if
the SEQ is very long and N very small.

Regards,

Michael.

**Comment by NicolasPetton** [comment]
Michael Heerdegen notifications@github.com writes:

> I don't understand the consistency argument any more.

That's because I was simply wrong :-)

> BTW, calling `seq-length' in that defgeneric seems quite inefficient if
> the SEQ is very long and N very small.

There's an optimized version for lists down the file.

Nico

**Comment by ghost** [comment]
Nicolas Petton notifications@github.com writes:

> There's an optimized version for lists down the file.

Ah, ok.

Thanks for fixing.
