### ISSUE TITLE
What's the use of the implementation of seq-copy for streams?

### ISSUE THREAD

**Issue by ghost** [NicolasPetton/stream#5]
Hey,

we have

```
(cl-defmethod seq-copy ((stream stream))
  "Return a shallow copy of STREAM."
  (stream-cons (stream-first stream)
               (stream-rest stream)))
```

With that implementation, elements generated newly in the copy also magically appear in the original.

I tested with the following:

```
(defun make-test-stream ()
  (stream-make (pcase (read-string "Enter a string, empty string to cancel: ")
                 ("" nil)
                 (s   (cons s (make-test-stream))))))

;; a test - just eval
(seq-into-sequence (make-test-stream))
```

Now try

```
(setq stream (make-test-stream))

(setq copy-of-stream (seq-copy stream))

(seq-into-sequence copy-of-stream)

(seq-into-sequence stream)
```

end of test.

And since we have no destructive stream operations (and probably will never have), we could just as well write

```
(cl-defmethod seq-copy ((stream stream))
  "Return a shallow copy of STREAM."
  stream)
```

with other words, an implementation of identity, the function is not useful.

Do I miss something?

**Comment by NicolasPetton** [comment]
Michael Heerdegen notifications@github.com writes:

We need an implementation of `seq-copy` to for streams to be
`seq`-ables.  The current implementation could be seen as a shallow
copy, thus sharing the cells of the streams, like shallow copies of
lists share the same cons cells.

I agree that another way to do it might be more useful, or that a deep
copy could be useful as well, but with the nature of streams, I don't
know how to do it.

Note that it's not identity though, it's a shallow copy.

Nico

**Comment by ghost** [comment]
Nicolas Petton notifications@github.com writes:

> I agree that another way to do it might be more useful, or that a deep
> copy could be useful as well, but with the nature of streams, I don't
> know how to do it.

I'm not really sure what a deep copy would be.

> Note that it's not identity though, it's a shallow copy.

Yes, I know, but it doesn't make a difference in practice, since we have
no destructive operations for streams, unlike most other seq variants.

So if you don't plan to modify the internal structure of a stream like

```
(setcdr stream some-new-function)
```

(and we don't want that anyone does this), you can just change any
occurrence of

```
(seq-copy stream)
```

with just

```
stream
```

in any program without any user visible effect.

**Comment by NicolasPetton** [comment]
Michael Heerdegen notifications@github.com writes:

> (and we don't want that anyone does this), you can just change any
> occurrence of
> 
> ```
> (seq-copy stream)
> ```
> 
> with just
> 
> ```
> stream
> ```
> 
> in any program without any user visible effect.

Not exactly, because you need `(eq stream (seq-copy stream))` to return
`nil`.

**Comment by ghost** [comment]
Nicolas Petton notifications@github.com writes:

> Not exactly, because you need `(eq stream (seq-copy stream))` to return
> `nil`.

you probably mean non-nil?  Ok, that's indeed a difference.  But for the
empty list, this isn't true either.

**Comment by NicolasPetton** [comment]
Michael Heerdegen notifications@github.com writes:

> you probably mean non-nil?  Ok, that's indeed a difference.  But for the
> empty list, this isn't true either.

No, I did mean nil.  A copy, even sharing the same elements, should not
be the same object as the original:

```
(let ((str (stream '(1 2 3))))
 (eq str (seq-copy str)))
```

**Comment by ghost** [comment]
Nicolas Petton notifications@github.com writes:

> A copy, even sharing the same elements, should not be the same object
> as the original:
> 
> (let ((str (stream '(1 2 3))))
> (eq str (seq-copy str)))

Ok, but how is this useful?  As I said, this is not fulfilled for other
sequences, e.g. lists.

Anyway, not really a problem here.  Feel free to close, thanks.

**Comment by NicolasPetton** [comment]
It is consistent with lists 

```
(let ((lst '(1 2 3)))
   (eq lst (seq-copy lst)))
```

**Comment by NicolasPetton** [comment]
Ok, closing the issue.
