### ISSUE TITLE
More functions?

### ISSUE THREAD

**Issue by cpitclaudel** [NicolasPetton/stream#8]
Hey Nicolas,

What would you think of adding more folds to `seq.el` and `stream.el`? We already have one (`reduce`), but we could add `foldr`.

Additionally, what do you think of adding functions such as `enumerate` (`a b c d …` → `(a . 0) (b . 1) (c . 2) …`), or `sum`?

**Comment by NicolasPetton** [comment]
What would be the advantage of enumerate over `seq-map-indexed`?

**Comment by cpitclaudel** [comment]
None; I just missed it and reimplemented it a few times already :/ What about an alias? Or I can create a post on emacs.stackexchange for future reference.

**Comment by NicolasPetton** [comment]
Clément Pit--Claudel notifications@github.com writes:

> None; I just missed it and reimplemented it a few times already :/
> What about an alias?

Why not an alias.  What did you have in mind?

**Comment by cpitclaudel** [comment]
I think `seq-enumerate` would work nicely; that's what python calls it, and searching for `equivalent of python enumerate` returns plenty of results mentioning Java, C#, matlab and others. What do you think?

**Comment by NicolasPetton** [comment]
Clément Pit--Claudel notifications@github.com writes:

> I think `seq-enumerate` would work nicely; that's what python calls
> it, and searching for `equivalent of python enumerate` returns plenty
> of results mentioning Java, C#, matlab and others. What do you think?

What does `enumerate` do in Python?

**Comment by cpitclaudel** [comment]
Transforms an iterator (stream) `x0, x1, x2 ...` into the iterator `(0, x0), (1, x1), (2, x2), ...`.

``` python
>>> seasons = ['Spring', 'Summer', 'Fall', 'Winter']
>>> list(enumerate(seasons))
[(0, 'Spring'), (1, 'Summer'), (2, 'Fall'), (3, 'Winter')]
```

**Comment by NicolasPetton** [comment]
Clément Pit--Claudel notifications@github.com writes:

> Transforms and iterator (stream) `x0, x1, x2 ...` into the stream `(0,
> x0), (1, x1), (2, x2), ...`.

Then it's quite different from `seq-map-indexed`, which maps over a
sequence (or stream), applying a function that takes 2 arguments: the
item of the collection and its index within that collection.
